### ISSUE TITLE
Balancing circuit

### ISSUE THREAD

**Issue by smarley2** [blinken/power-rail-probe#2]
Hi, are you thinking in a balancing circuit for the cells while charging?
Seems that actual charging IC does not do it.

**Comment by blinken** [comment]
Thanks for the comment!

That's correct, the charging IC just charges the cells in series. I don't feel cell balancing is necessary at this stage - my expectation is that the current draw from the cells is so small that it's unlikely they'll become unbalanced in a short space of time. 

Adding a balanced charger would be complex with the current switched-ground design, bearing in mind it needs to be out of circuit during operation to avoid any introduced noise.

Potentially, once every couple of years, the user might need to remove the cells and charge them individually, but that seems like an ok compromise.
